version: 2.1
jobs:
  build:
    docker:
     - image: cimg/node:18.17.1
    #  - image: circleci/node:18  # Use Node.js 18
    # Steps to the job
    steps:
      - checkout
      - run: npm cache clean --force
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 \
              libasound2 libatk1.0-0 libatk-bridge2.0-0 libnss3 libgbm-dev \
              libpango-1.0-0 libcups2 libxkbfile1
      - run: npm ci
      - run: npx playwright install --with-deps
      - run:
          name: Start virtual display
          command: |
            Xvfb :99 -screen 0 1920x1080x24 &
            export DISPLAY=:99
      - run:
          name: Run Playwright specs
          command: npx playwright test
          # command: npm run test