version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    # Steps to the job
    steps:
      - checkout
      - run: npm i -D @playwright/test@1.17.2
      - run: npx playwright install
      - run:
          name: Run Playwright specs
          command: npm run test