version: 2.1
executors:
  node-browser-executor:
    docker:
      - image: circleci/node:18-browsers

jobs:
  build:
    executor: node-browser-executor
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm test  # Ensure `npm` commands are correct and functional
workflows:
  version: 2
  build_and_test:
    jobs:
      - build