version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:18-browsers
    # Steps to the job
    steps:
      - checkout
      - run: npm i -D @playwright/test
      - run: npx playwright install
      - run:
          name: Clear npm cache
          command: npm cache clean --force
          name: Run Playwright specs
          command: npm run test