version: 2.1
jobs:
  build:
    docker:
     - image: cimg/node:18.17.1
    #  - image: circleci/node:18  # Use Node.js 18
    # Steps to the job
    steps:
      - checkout
      - run: npm cache clean --force
      - run: npm ci
      - run: npx playwright install
      - run:
          name: Run Playwright specs
          command: npm run test src/__tests__/app.spec.js